# Generated by Django 4.2.2 on 2023-06-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'others')], max_length=1)),
            ],
        ),
    ]
